table Sheet1
	lineageTag: 074f4774-27eb-486f-8bb4-9a2749785c2d

	column Column1
		dataType: string
		lineageTag: f181761c-141e-48de-99dc-790b0ac32c53
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		lineageTag: 504c7233-c2c3-48e5-a7c8-ac246e205a8a
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	partition Sheet1 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\satya\Downloads\Telegram Desktop\Insurance+Customer+Feedback.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Sheet1_Sheet,{{"Column1", type text}, {"Column2", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

